New post/summer interns 2017
finn-no/tech.finn.no pull request #41
Opened 2017-08-08 13:13 UTC by hoxmark

Blog post from the summer interns.

2017-08-08 13:18 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +There were several steps to go through before we could launch our solution. We were lucky to get the opportunity to develop it the whole way from backend to frontend. As we have understood, this is a
the backtick in "FINN.no`s" breaks the entire document :P

2017-08-09 10:04 UTC, theneva requested changes
It would be cool if you said something about how the surveys were overwhelmingly positive, yet almost no one actually used the feedback system. Other than that (and the comments I've left), this looks great to me!

~I'll fix the grammar stuff~

Edit: I fixed the grammar stuff, but please look at the comments even though GitHub reports them as "outdated"

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +During the first week of the summer internship we (the interns) were introduced to FINN.no, its systems and our coaches for the summer project; Martin, the brilliant programmer and Ingrid, the amazin
a brainstorming session ~were~ was held

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +In the past 2 months two concepts have been realized, with quiet surprising results and developments. But you have to read the rest of the document to know exactly what surprising developments took p
with ~quiet~ quite surprising

I hope

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Have you ever created an ad and received no feedback, no likes and no messages? This is the reality of approximately 50 % of all ads published on FINN Torget in Norway. Imagine there was a way for ad
Imagine *if* there was

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +“Tilbakemelding” is one possibility. Tilbakemelding is a button located at the front page of an ad for all potential buyers to see and use. If a user do not like an ad, and feel that sending a messag
a user ~do~ does not, and ~feel~ feels that

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +After implementing the solution and launching it on FINN.no website, it was determined the new functionality was used by barely any users. Some tears were shed, and a new direction was chosen. It was
users can ~chose~ choose specific

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +There were several steps to go through before we could launch our solution. We were lucky to get the opportunity to develop it the whole way from backend to frontend. As we have understood, this is a
FINN.no’s tested and ~proved~ proven microservices architecture

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +There were several steps to go through before we could launch our solution. We were lucky to get the opportunity to develop it the whole way from backend to frontend. As we have understood, this is a
Docker and Docker Compose ~was~ were utilized

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +There were several steps to go through before we could launch our solution. We were lucky to get the opportunity to develop it the whole way from backend to frontend. As we have understood, this is a
dependencies and environments ~was~ were identical

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Each tag that's chosen by a user were stored in the database connected to different types of data like the Id’s of the seller, ad and the person clicking on the tags. We used Java, Spring Boot and In
Each tag that's chosen by a user ~were~ was stored

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Each tag that's chosen by a user were stored in the database connected to different types of data like the Id’s of the seller, ad and the person clicking on the tags. We used Java, Spring Boot and In
Spring Boot ~were~ was not familiar

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Each tag that's chosen by a user were stored in the database connected to different types of data like the Id’s of the seller, ad and the person clicking on the tags. We used Java, Spring Boot and In
> Spring Boot were not familiar to all of us, but it turns out that it’s a neat way for handling with different types of REST API like we had to in this project.

What does this sentence mean?

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Each tag that's chosen by a user were stored in the database connected to different types of data like the Id’s of the seller, ad and the person clicking on the tags. We used Java, Spring Boot and In
Thankfully FINN.no has ~it’s~ its own implementation

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Each tag that's chosen by a user were stored in the database connected to different types of data like the Id’s of the seller, ad and the person clicking on the tags. We used Java, Spring Boot and In
> so it spares developers

is "saves" a better word?

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Several prototypes were designed using Sketch and Invision, with people inhouse and on the streets helping us evaluate the design. The tests helped us rename several of the tags, helped us deciding t
It was revealed *that* most users did not notice

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Using an automated system rather than user feedback would also minimize the possibility of buyers misusing the feedback module (giving inaccurate/wrong feedback). This system could analyse the amount
> the possibility of buyers misusing the feedback module

misusing/abusing?

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +Using an automated system rather than user feedback would also minimize the possibility of buyers misusing the feedback module (giving inaccurate/wrong feedback). This system could analyse the amount
the ~prize~ price 😛

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +During the first weeks of the project, several surveys regarding aspects of “Tilbakemelding” was given to a set of FINN users. Based on these surveys, we know advertisers want advice in how to improv
several surveys regarding aspects of “Tilbakemelding” ~was~ were given

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +# Project 2 : Redesign ad dashboard
I would remove the space between `2` and `:`

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +After finishing “Tilbakemelding”, it was decided to do a redesign of the ad dashboard page in order to improve advertiser’s user experience. As can be seen on the picture, several of the buttons have
to improve ~advertiser’s~ advertisers' user experience

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +After finishing “Tilbakemelding”, it was decided to do a redesign of the ad dashboard page in order to improve advertiser’s user experience. As can be seen on the picture, several of the buttons have
The old message system ~have~ has been

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +After finishing “Tilbakemelding”, it was decided to do a redesign of the ad dashboard page in order to improve advertiser’s user experience. As can be seen on the picture, several of the buttons have
> to help advertisers be more aware of their ads and its possibilities.

What does this mean?

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +The redesigned ad dashboard page has been created using Node.js and React. By splitting FINN.no into multiple smaller microservices it allows developers to create/modify pages, while still keeping de
We still ~utilizes~ utilize existing

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +The redesigned ad dashboard page has been created using Node.js and React. By splitting FINN.no into multiple smaller microservices it allows developers to create/modify pages, while still keeping de
~ finn~ FINN

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +The redesigned ad dashboard page has been created using Node.js and React. By splitting FINN.no into multiple smaller microservices it allows developers to create/modify pages, while still keeping de
the use of Finnlets which ~creates~ create the

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +New prototypes in Sketch and Invision were made. According the user tests in FINN.no’s lab, most people understood the new system, and felt it was fitting nicely into FINN.no current website. Several
> it took some time before the advices into making a better ad was discovered

"advice for improving the ad", or something along those lines?

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +New prototypes in Sketch and Invision were made. According the user tests in FINN.no’s lab, most people understood the new system, and felt it was fitting nicely into FINN.no current website. Several
were mostly concerned *with* the

2017-08-09 10:04 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +As mentioned, the advices into improving an ad was not noticed by most users, even though they were perceived as helpful and motivating when spotted. By making the advices more noticeable (bigger, mo
> the advices into improving

Here, too, I think "the advice for improving" is better

2017-08-09 10:08 UTC, theneva commented
Also, you should add yourselves to https://github.com/finn-no/tech.finn.no/blob/gh-pages/_data/authors.yml (I *think*)

2017-08-09 10:15 UTC, theneva commented on _posts/2017-08-08-summerinterns-2017.md
> +The redesigned ad dashboard page has been created using Node.js and React. By splitting FINN.no into multiple smaller microservices it allows developers to create/modify pages, while still keeping de
nvm

2017-08-10 07:44 UTC, SimenB commented on _posts/2017-08-08-summerinterns-2017.md
> +- Kristoffer K.Larsen
missing space

2017-08-10 08:00 UTC, hoxmark commented on _posts/2017-08-08-summerinterns-2017.md
> +- Kristoffer K.Larsen
Thanks!

2017-08-10 12:08 UTC, merged